Clean up a bunch of the redundant code
qbcore-framework/qb-spawn pull request #11
Opened 2021-09-07 17:34 UTC by Tastyfish

Cleans up loads of redundant code in the `setCam` and `spawnPlayer` event handlers, so it's more coherent and more clear what's different between the spawn types.

2021-09-10 19:20 UTC, FreakOutModz requested changes

2021-09-10 19:20 UTC, FreakOutModz commented on client.lua
> +        PreSpawnPlayer()
wrong, text always is `preSpawnPlayer`. Never start with a capital letter.

2021-09-10 19:20 UTC, FreakOutModz commented on client.lua
> +local function PostSpawnPlayer(ped)
Please change typo to `postSpawnPlayer`

2021-09-10 19:20 UTC, FreakOutModz commented on client.lua
> +local function PreSpawnPlayer()
Please change typo as mentionned `preSpawnPlayer`

2021-09-10 19:20 UTC, FreakOutModz commented on client.lua
> +        PostSpawnPlayer()
Change typo here

2021-11-01 07:06 UTC, Tastyfish commented
@FreakOutModz Sorry, I never got notified of the comments in this PR. As for your comments, is this a convention rule for local functions? If so, `qb-core` itself doesn't follow that convention.

2021-11-01 07:24 UTC, merged

2021-11-01 15:42 UTC, FreakOutModz commented
Is not a real "rule", but is how should code look. `Qb-core` didn't follow this way but we can change everything easily!

2021-11-01 17:32 UTC, Tastyfish commented
Ah, fair enough. I'm fine with any coding guideline rules, I was just legitimately confused.

2022-01-11 03:11 UTC, zfbx commented
@Tastyfish I know this conversation is long over I know but to clarify it's a best practice to give local variables a lowercase first character and use an uppercase letter for global variables to easily be able to distinguish between them